### PR TITLE
Add worker version column in workersTable for easier App/Agent versio…

### PR DESCRIPTION
**Pull request by tchavei**
…n control/overview

Pokemod MITM Aegis works with App and Agent versions which are independent of each other. Agent versions are pushed server side while App versions have to be installed by the user. Since Rotom already demands version_code to be sent in the Welcome Message, the worker version is present and can be displayed in the worker's table to make it easier for the user to see exactly on what version each of his device is working and with this PR it will also allow to see if each device has the latest agent deployed (which are only deployed on restart) as in this screenshot:

image

### CODE REVIEW

**Comment by jfberry** [comment]
I'm not clear on why individual workers would have different versions? Surely this is something that is on the control connection only?

**Comment by Fabio1988** [comment]
It seems atlas uses two different versions, app and agent. App version is sent on device welcome.. and agent version on worker hello.... I also asked why that's needed, aegis could always use agent version, not app version.

Is it not possible to extract app version from agent version? @cyberaltra

**Comment by jfberry** [comment]
If they are not different per worker (why would they be?) then it should be sent on the control connection surely (if it is relevant)

**Comment by Fabio1988** [comment]
> If they are not different per worker (why would they be?) then it should be sent on the control connection surely (if it is relevant)

Exactly, that's what I told to root as well... Maybe Cyber can clarify, as I don't get it as well :)

All worker have same agent version

**Comment by jfberry** [comment]
Feels like app version is irrelevant and agent version should be sent in the control connection?

**Comment by jfberry** [comment]
Whatever the solution, if it doesn’t vary per worker then this is the wrong way to display it IMO

**Pull request closed without merging**
