### PR TITLE
fix: ping, uses timeOut stuff

### PR DESCRIPTION
**Pull request by Furtif**
### In this PR you will find the following modifications:
 - Time control for different pings and waiting for a response (I set 15 seconds as a default for devices and/or vps  ultra-slow), other than that, if the response is fast, these changes do not alter the basic functioning in any way, and/or help to have something more solid without need to mark things that will be placed online later.
 - Rotom protos update, although this is not a necessity.
 - Add rotom version infos style this: 
image

### CODE REVIEW

**Comment by jfberry** [comment]
Thank you for your changes.  Please split into 4 PRs as each has a different risk/discussion associated with it.

For the main part of the request, I believe that an alternative model is preferable:
* the internal isAlive can continue to work as it is, but be renamed to some heartbeat value (eg 'heatbeatReceived')
* the isAlive flag can be set to false on disconnection only so represents a true 'disconnected' value that the UI and the api are returning the connection status rather than the internal heartbeat value
There is no need to have more complex logic behind an additional timeout

**Comment by Furtif** [comment]
> Thank you for your changes. Please split into 4 PRs as each has a different risk/discussion associated with it.
> 
> For the main part of the request, I believe that an alternative model is preferable:
> 
> * the internal isAlive can continue to work as it is, but be renamed to some heartbeat value (eg 'heatbeatReceived')
> * the isAlive flag can be set to false on disconnection only so represents a true 'disconnected' value that the UI and the api are returning the connection status rather than the internal heartbeat value
>   There is no need to have more complex logic behind an additional timeout

fine

**Comment by Furtif** [comment]
ok ,
And the confusion is so great,
Following your reasoning, the next time a protos has more than 20 lines of changes, I won't do anything, and ask Niantic to divide it into parts

**Comment by jfberry** [comment]
The protos is not the bit which is controversial but confuses the PR (and is not needed for rotom anyway as you say)
Ws dependency could cause a performance or stability regression so should be tested separately
Version isn’t really an issue

**Comment by Furtif** [comment]
> The protos is not the bit which is controversial but confuses the PR (and is not needed for rotom anyway as you say) Ws dependency could cause a performance or stability regression so should be tested separately Version isn’t really an issue

WS is fine

**Comment by Furtif** [comment]
It was precisely the only updated dep, the rest I didn't change

**Comment by jfberry** [comment]
> WS is fine

You say, but we have had regressions with this library before so we will accept this only with some measured testing

**Comment by Furtif** [comment]
> You say, but we have had regressions with this library before so we will accept this only with some measured testing

ok go back to 8.5.0 old

**Comment by Furtif** [comment]
> > WS is fine
> 
> You say, but we have had regressions with this library before so we will accept this only with some measured testing

fixed

**Comment by jfberry** [comment]
I have pushed an untested branch with my intended way to fix the isAlive column: Let me know if works for your use case, #45 
I do not see any reason to change the way heartbeats work
If you would like version and other changes please raise in seperate PRs

**Comment by Furtif** [comment]
> I have pushed an untested branch with my intended way to fix the isAlive column: Let me know if works for your use case, #45 I do not see any reason to change the way heartbeats work If you would like version and other changes please raise in seperate PRs

it i thinks have same  bug ... but ... ok xd

**Comment by Fabio1988** [comment]
> it i thinks have same bug ... but ... ok xd

Same bug,.but fixed in a different way

**Pull request closed without merging**
